DELETE FROM ADMINISTRADORENTITY_CAMBIOENTITY  WHERE 1=1;
DELETE FROM ADMINISTRADORENTITY_NOTIFICACIONENTITY  WHERE 1=1;
DELETE FROM CAMBIOENTITY WHERE 1=1;
DELETE FROM NOTIFICACIONENTITY WHERE 1=1;
DELETE FROM ESTADOWEBENTITY WHERE 1=1;
DELETE FROM SITIOWEBENTITY_ADMINISTRADORENTITY  WHERE 1=1;
DELETE FROM ADMINISTRADORENTITY  WHERE 1=1;
DELETE FROM DEPENDENCIAENTITY WHERE 1=1;
DELETE FROM SITIOWEBENTITY_SITIOWEBENTITY  WHERE 1=1;
DELETE FROM SITIOWEBENTITY_TECNOLOGIAENTITY  WHERE 1=1;
DELETE FROM TECNOLOGIAENTITY WHERE 1=1;
DELETE FROM USUARIOENTITY_TICKETENTITY  WHERE 1=1;
DELETE FROM TICKETENTITY WHERE 1=1;
DELETE FROM SITIOWEBENTITY WHERE 1=1;
DELETE FROM PLATAFORMADEDESPLIEGUEENTITY  WHERE 1=1;
DELETE FROM USUARIOENTITY WHERE 1=1;


ALTER TABLE ADMINISTRADORENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE CAMBIOENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE DEPENDENCIAENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ESTADOWEBENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE NOTIFICACIONENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE PLATAFORMADEDESPLIEGUEENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SITIOWEBENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE TECNOLOGIAENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE TICKETENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE USUARIOENTITY ALTER COLUMN ID RESTART WITH 1;


INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',NULL,5471774913331200,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,49180931772121088,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,83890761514352640,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,82590065028497408,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,89677319412645888,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,17875385450496000,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',NULL,74868967960739840,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,16038293720268800,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,49398385966317568,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,13751353557909504,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,31430849845002240,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',NULL,28263856925048832,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,70543012475699200,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,68393991229407232,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,49638878365089792,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,92674905937543168,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,77102539933220864,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',NULL,81839699882147840,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',NULL,90051359524519936,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,54902631369277440,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');


INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('tggayp.jctrwv@hrvwfwi.com','Sistemas','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('hhxwf.cepic@fqawpl.com','Industrial','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('oaxhe.uhgiut@vsio.com','Fisica','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('fhrpndp.qbhdte@ilpvf.co','Quimica','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('tnbqnwdlc.gfrxxrs@ahu.com','Biologia','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('vdkumtgb.eughlj@pzqn.org','Sistemas','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('gijsss.vuhsn@wal.co','Matematicas','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('rydemrvcx.jswjs@rqt.co','Industrial','+57 3132266270');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('hskgwqx.xhpowov@rpq.com','Sistemas','+57 3132266270');


INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Jorge','Paquete','https://www.sueitwep.com/jknsxdmpqkt/hxntgc.php','74.0.8600');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Stella','Paquete','http://www.oggnudd.co/qtcrxvol/toevzu.html','78.4.3500');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Marvin','Lenguaje','http://www.njtkzrf.org/tkuflavktfl/lxqsxom.aspx','62.4.9800');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Ernest','Lenguaje','http://www.hpxqfood.co/bwutovrz/xptdpb.php','15.3.2800');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Aaliyah','Lenguaje','https://www.devgzrs.org/nagpxhvry/ceflrggjf.php','61.7.9900');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Juan','Software','https://www.jsdcjhx.net/yitvhhur/jtvqvhqs.php','53.8.9100');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Salvador','Lenguaje','https://www.ofzntmnem.net/bgeobxjcm/nesrggx.html','14.7.6600');


INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('mxwyuu.unadt@pafm.co','Anna Lee',13,'pxy15pjb3ep','+621 4 845 1216','Lauren06');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('cfccs.scmnkmc@tmxbns.co','Alyssa Lewis',9,'ts5kfv4tl','+540 6 647 3806','Ernest529');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('qepfh.ksawel@djn.org','Eliana Richardson',20,'ff02me4uk','+951 4 477 7586','Salvador6');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('rtyju.kpyqqhu@bdbc.com','Samantha Sanchez',0,'mdk5556qsl261vxr','+745 9 838 4675','Andy3');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('fxjywoqoi.gberknh@idv.co','Madison Phillips',18,'vwd756zm8dzr','+691 8 235 3935','Ray5');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('rmpjfzd.wjfvn@ywo.com','Savannah Perez',20,'nk741tvt72ux','+413 0 412 9858','Aria4');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('ddrmfgi.ivlueq@xeg.org','Piper Edwards',14,'kgc3tx4kr','+503 2 488 1803','Juan138');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('nyior.zthht@bbbl.org','Ella Reyes',6,'gq883hg75lt','+097 3 895 4553','Stella84');


/*Estos datos se esta generando de forma extraña*/

INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',8,'CO 2591338','SAAS','144.66.241.32',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',4,'Cyrix FasMath CX83D87 33 GP','PAAS','26.12.22.68',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',7,'Cyrix 486 DX2 66GP Light Green H/S','ONPREMISE','65.17.95.98',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',6,'AMD Elan SC520100AC','IAAS','28.142.59.52',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',7,'AMI S6551P','IAAS','124.23.17.56',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',4,'AMD K6 200 ALR 2.9V','PAAS','66.28.36.17',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',9,'AMD K6-2 350 AFQ 2.2V','ONPREMISE','35.244.17.45',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',5,'AMD K6 300 AFR 2.2V','ONPREMISE','22.27.89.22',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',9,'AMD 486 DX2 80','SAAS','23.122.77.135',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',8,'AMD K6 200 ALR 2.9V (Logo)','PAAS','48.77.19.67',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',2,'AMD K6-2 475 AFX 2.2V','IAAS','51.15.95.43',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',6,'AMI S6809P','PAAS','28.27.71.85',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',6,'Cyrix FasMath CX83S87 25 JP','PAAS','14.27.11.53',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',4,'AMD K5 PR100 ABR','ONPREMISE','37.55.52.32',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',4,'AMD R80186','IAAS','15.82.38.29',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',6,'AMD K6-2 400 AFR 2.2V','IAAS','62.42.82.76',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',4,'AMD K6-2 266 AFR 2.2V (Black Print)','ONPREMISE','27.48.94.42',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',3,'Cyrix FasMath CX83D87 40 GP','SAAS','144.26.16.26',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',4,'AMD K6-2 266 AFR 2.2V (Black Print)','SAAS','16.43.88.77',1);

  
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (2,'ADMINISTRATIVO','Similarly , janitor is driving all day long. ','29.01.1774','mibanner.uniandes.edu.co','Banner Uniandes','Onversely , crooked lab rat isnt leaving the school. ',1,'mibanner.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (90,'INFORMATIVO','Nonetheless , fat scientists are making dinner. ','28.05.1810','sistemas.uniandes.edu.co','Sistemas Uniandes','Hence , obedient janitors were leaving the school. ',2,'sistemas.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (40,'OTRO','Namely , massive soldier has been escaping. ','26.01.1957','uniandes.edu.co','Uniandes','In comparison , John wrote letters. ',3,'uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (82,'OTRO','Bird wrote essays. ','02.05.1824','sisinfo.uniandes.edu.co','Sis Info','Otherwise , teacher has waited for the bus. ',4,'sisinfo.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (45,'OTRO','Furthermore , heavy pilgrims are going to school. ','13.09.1934','labsis.uniandes.edu.co','Laboratorio Sistemas','Consequently , relieved programmer has been leaving the house. ',5,'labsis.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (32,'INFORMATIVO','Certainly , obedient producer hasn''t been running late. ','05.09.1922','industrial.uniandes.edu.co','Ingenieria Industrial','Namely , early boxer wrote essays. ',6,'industrial.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (7,'ADMINISTRATIVO','Besides , crooked fighters haven''t been writting essays. ','13.01.1917','sicuaplus.uniandes.edu.co','Sicua','Indeed , strong scientists are putting the fire out.',7,'sicuaplus.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (31,'ACADEMICO','Incidentally , clever bird has left the house. ','27.08.1925','matriculas.uniandes.edu.co','Matriculas','Boxers were going home for lunch. ',8,'matriculas.uniandes.edu.co');
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID,URL) VALUES (50,'OTRO','Next , blue airplanes aren''t running late. ','20.11.1901','registro.uniandes.edu.co','Admisiones y registro','Dogs have been writting letters. ',9,'registro.uniandes.edu.co');



INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('udyudi.byyue@hddun.co',5,'Charlotte Robinson','Auditor','ry0pg2csz','+503 8 514 3881',1,1);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('tiior.ktsgkk@prt.org',4,'Sadie Ward','Appraiser','fnd6bho73la','+748 4 958 0723',2,2);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('oljdk.rgkoc@ltj.co',5,'Savannah Perez','Budget Analyst','ymf3eqg1225rc','+811 4 556 3628',3,3);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('rtvhv.foicw@kftj.co',1,'Victoria Gray','Banking Manager','zjo8av8mwm','+824 4 175 2872',4,4);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('umwhcm.tjxma@hch.org',1,'Madison Phillips','Banking Analyst','ju6rhv1hu','+289 6 713 2279',5,5);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('dchvhj.tngubi@wvp.com',2,'Riley Hall','Accountant','rd62tor5teu','+993 1 812 0213',6,6);


INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','ACTIVO','01.01.2019',        1);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','INACTIVO','01.01.2019',      2);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','INACTIVO','01.01.2019',      3);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','OTROS','01.01.2019',         4);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','ERROR','01.01.2019',         5);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','ACTIVO','01.01.2019',        6);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','ACTIVO','01.01.2019',        7);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','INACTIVO','01.01.2019',     8);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION1','ACTIVO','01.01.2019',        9);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','ACTIVO','01.01.2019',        1);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','INACTIVO','01.01.2019',      2);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','INACTIVO','01.01.2019',      3);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','OTROS','01.01.2019',         4);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','ERROR','01.01.2019',         5);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','ACTIVO','01.01.2019',        6);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','ACTIVO','01.01.2019',        7);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','INACTIVO','01.01.2019',     8);
INSERT  INTO ESTADOWEBENTITY(DESCRIPCION, ESTADO, FECHACAMBIO, SITIOASOCIADO_ID) VALUES ('DESCRIPCION2','ACTIVO','01.01.2019',        9);








