DELETE FROM ADMINISTRADORENTITY_CAMBIOENTITY  WHERE 1=1;
DELETE FROM ADMINISTRADORENTITY_NOTIFICACIONENTITY  WHERE 1=1;
DELETE FROM CAMBIOENTITY_SITIOWEBENTITY  WHERE 1=1;
DELETE FROM CAMBIOENTITY WHERE 1=1;
DELETE FROM NOTIFICACIONENTITY WHERE 1=1;
DELETE FROM ESTADOWEBENTITY WHERE 1=1;
DELETE FROM SITIOWEBENTITY_ADMINISTRADORENTITY  WHERE 1=1;
DELETE FROM ADMINISTRADORENTITY  WHERE 1=1;
DELETE FROM DEPENDENCIAENTITY WHERE 1=1;
DELETE FROM SITIOWEBENTITY_SITIOWEBENTITY  WHERE 1=1;
DELETE FROM SITIOWEBENTITY_TECNOLOGIAENTITY  WHERE 1=1;
DELETE FROM TECNOLOGIAENTITY WHERE 1=1;
DELETE FROM USUARIOENTITY_TICKETENTITY  WHERE 1=1;
DELETE FROM TICKETENTITY WHERE 1=1;
DELETE FROM SITIOWEBENTITY WHERE 1=1;
DELETE FROM PLATAFORMADEDESPLIEGUEENTITY  WHERE 1=1;
DELETE FROM USUARIOENTITY WHERE 1=1;


ALTER TABLE ADMINISTRADORENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE CAMBIOENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE DEPENDENCIAENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ESTADOWEBENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE NOTIFICACIONENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE PLATAFORMADEDESPLIEGUEENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SITIOWEBENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE TECNOLOGIAENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE TICKETENTITY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE USUARIOENTITY ALTER COLUMN ID RESTART WITH 1;


INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',NULL,5471774913331200,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,49180931772121088,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,83890761514352640,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,82590065028497408,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,89677319412645888,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,17875385450496000,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',NULL,74868967960739840,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,16038293720268800,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,49398385966317568,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,13751353557909504,'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,31430849845002240,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',NULL,28263856925048832,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,70543012475699200,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',NULL,68393991229407232,'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,49638878365089792,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',NULL,92674905937543168,'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,77102539933220864,'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',NULL,81839699882147840,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.',NULL,90051359524519936,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO CAMBIOENTITY(DESCRIPCION,FECHACAMBIO,IDASOCIADO,LUGARCAMBIO,NUEVO,PREVIO) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?',NULL,54902631369277440,'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');


INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('tggayp.jctrwv@hrvwfwi.com','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('hhxwf.cepic@fqawpl.com','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('oaxhe.uhgiut@vsio.com','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('fhrpndp.qbhdte@ilpvf.co','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('tnbqnwdlc.gfrxxrs@ahu.com','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('vdkumtgb.eughlj@pzqn.org','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('gijsss.vuhsn@wal.co','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('rydemrvcx.jswjs@rqt.co','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('hskgwqx.xhpowov@rpq.com','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('ujodt.egeyh@akread.co','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('fxvrqyovw.ganywcy@dozm.org','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('fsmogbo.llyqtrv@nip.org','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('uqchkb.mqxhcr@gdd.co','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('lsorj.rzxyum@ekb.org','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('qwmlwijdw.yckhoe@yzbmcd.co','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('mxygs.xjjvw@fiyhazc.org','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('frmtv.ttguj@lok.org','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('jewlbgnq.cieoxj@png.org','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('pjoqv.mtlgd@brjl.org','Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');
INSERT INTO DEPENDENCIAENTITY(EMAIL,NOMBREDEPENDENCIA,TELEFONO) VALUES ('kfuub.mpx@zwc.org','Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?');


INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Jorge','Paquete','https://www.sueitwep.com/jknsxdmpqkt/hxntgc.php','74.0.8600');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Stella','Paquete','http://www.oggnudd.co/qtcrxvol/toevzu.html','78.4.3500');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Marvin','Lenguaje','http://www.njtkzrf.org/tkuflavktfl/lxqsxom.aspx','62.4.9800');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Ernest','Lenguaje','http://www.hpxqfood.co/bwutovrz/xptdpb.php','15.3.2800');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Aaliyah','Lenguaje','https://www.devgzrs.org/nagpxhvry/ceflrggjf.php','61.7.9900');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Juan','Software','https://www.jsdcjhx.net/yitvhhur/jtvqvhqs.php','53.8.9100');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Salvador','Lenguaje','https://www.ofzntmnem.net/bgeobxjcm/nesrggx.html','14.7.6600');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Aria','Paquete','http://www.tauionol.net/hnttkfxz/krxapme.aspx','71.1.6100');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Arianna','Software','http://www.geafypmw.org/dlyatmsfyk/lkdsnqck.html','38.7.5900');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Lauren','Software','http://www.lgsptyau.org/hitoqgcvzwc/buavuv.htm','14.4.5800');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.','Nicholas','Paquete','https://www.prhlqqr.com/ftdevganbt/xxukitd.aspx','13.7.7800');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Lawrence','Software','http://www.nvwccron.net/emtpsixfhov/eorbbp.aspx','11.2.4200');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Andy','Software','http://www.qtdlmsquhkk.com/wyckujdvs/oihedqzoa.aspx','45.0.7300');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Ray','Paquete','https://www.pkxlptuj.net/snsjnlbsv/glaxdpivs.html','57.4.2000');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Edward','Lenguaje','http://www.eqfnsrwx.net/sthaevosl/kgfyjn.aspx','52.0.1500');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?','Jerome','Paquete','http://www.bhkpesyqwp.net/qsjgbmxdc/fdfskx.php','92.9.3100');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','Roland','Lenguaje','https://www.gweonudpx.com/fkpdlkqd/qgzjbng.aspx','54.0.1500');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Alex','Lenguaje','https://www.bchrbzh.net/imawexhs/vuccij.htm','18.0.1500');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?','Gilbert','Paquete','http://www.vdrixjirqmk.com/xbttcxnqp/quvcfyg.aspx','23.2.6400');
INSERT INTO TECNOLOGIAENTITY(DESCRIPTION,NAME,TECHCATEGORY,URL,VERSION) VALUES ('Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','Charlie','Software','https://www.sxhtwjirp.net/jstmhryi/mtvmzdj.htm','51.5.0200');


INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('mxwyuu.unadt@pafm.co','Anna Lee',13,'pxy15pjb3ep','+621 4 845 1216','Lauren06');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('cfccs.scmnkmc@tmxbns.co','Alyssa Lewis',9,'ts5kfv4tl','+540 6 647 3806','Ernest529');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('qepfh.ksawel@djn.org','Eliana Richardson',20,'ff02me4uk','+951 4 477 7586','Salvador6');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('rtyju.kpyqqhu@bdbc.com','Samantha Sanchez',0,'mdk5556qsl261vxr','+745 9 838 4675','Andy3');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('fxjywoqoi.gberknh@idv.co','Madison Phillips',18,'vwd756zm8dzr','+691 8 235 3935','Ray5');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('rmpjfzd.wjfvn@ywo.com','Savannah Perez',20,'nk741tvt72ux','+413 0 412 9858','Aria4');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('ddrmfgi.ivlueq@xeg.org','Piper Edwards',14,'kgc3tx4kr','+503 2 488 1803','Juan138');
INSERT INTO USUARIOENTITY(EMAIL,NOMBRE,NUMEROTICKETS,PASSWORD,TELEFONO,USERNAME) VALUES ('nyior.zthht@bbbl.org','Ella Reyes',6,'gq883hg75lt','+097 3 895 4553','Stella84');


/*Estos datos se esta generando de forma extraña*/

INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',8,'CO 2591338','SAAS','144.66.241.32',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',4,'Cyrix FasMath CX83D87 33 GP','PAAS','26.12.22.68',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',7,'Cyrix 486 DX2 66GP Light Green H/S','ONPREMISE','65.17.95.98',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',6,'AMD Elan SC520100AC','IAAS','28.142.59.52',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',7,'AMI S6551P','IAAS','124.23.17.56',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',4,'AMD K6 200 ALR 2.9V','PAAS','66.28.36.17',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',9,'AMD K6-2 350 AFQ 2.2V','ONPREMISE','35.244.17.45',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',5,'AMD K6 300 AFR 2.2V','ONPREMISE','22.27.89.22',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',9,'AMD 486 DX2 80','SAAS','23.122.77.135',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',8,'AMD K6 200 ALR 2.9V (Logo)','PAAS','48.77.19.67',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',2,'AMD K6-2 475 AFX 2.2V','IAAS','51.15.95.43',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',6,'AMI S6809P','PAAS','28.27.71.85',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',6,'Cyrix FasMath CX83S87 25 JP','PAAS','14.27.11.53',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',4,'AMD K5 PR100 ABR','ONPREMISE','37.55.52.32',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',4,'AMD R80186','IAAS','15.82.38.29',0);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',6,'AMD K6-2 400 AFR 2.2V','IAAS','62.42.82.76',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('2800',4,'AMD K6-2 266 AFR 2.2V (Black Print)','ONPREMISE','27.48.94.42',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',3,'Cyrix FasMath CX83D87 40 GP','SAAS','144.26.16.26',1);
INSERT INTO PLATAFORMADEDESPLIEGUEENTITY(CLOCK,CORES,CPU,HOSTING,IP,ISVIRTUALIZACION) VALUES ('3600',4,'AMD K6-2 266 AFR 2.2V (Black Print)','SAAS','16.43.88.77',1);

  
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (2,'Bird Food','Similarly , janitor is driving all day long. ','29.01.1774','http:|-sw|ssw|w-w|-/s-/|s///s-///w|-/w.gif','Haverford College','Onversely , crooked lab rat isnt leaving the school. ',1);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (90,'Baking Ingredients','Nonetheless , fat scientists are making dinner. ','28.05.1810','http:.w--|/s-/-s/ww/-|ww-.s-/|s/-/w/.jpg','Princeton University','Hence , obedient janitors were leaving the school. ',2);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (40,'Breath Fresheners and Gums','Namely , massive soldier has been escaping. ','26.01.1957','https:||ww./w//-.s./|w|w||.gif','Pomona College','In comparison , John wrote letters. ',3);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (82,'Bandages & Gauzes','Bird wrote essays. ','02.05.1824','https:s-s|.gif','University of Notre Dame','Otherwise , teacher has waited for the bus. ',4);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (45,'Blush','Furthermore , heavy pilgrims are going to school. ','13.09.1934','http:w.jpg','Claremont McKenna College','Consequently , relieved programmer has been leaving the house. ',5);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (32,'Beans','Certainly , obedient producer hasn''t been running late. ','05.09.1922','https:ssw/ww/-w/.gif','Swarthmore College','Namely , early boxer wrote essays. ',6);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (7,'Body Art','Besides , crooked fighters haven''t been writting essays. ','13.01.1917','http:/-|//wws//..jpg','Amherst College','Indeed , strong scientists are putting the fire out.',7);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (31,'Cakes','Incidentally , clever bird has left the house. ','27.08.1925','https:ws-.w-w.gif','Northwestern University','Boxers were going home for lunch. ',8);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (50,'Bath Products','Next , blue airplanes aren''t running late. ','20.11.1901','http:-/||s/|w|ww/|//-////-|s||-//wwss|w.sww/w|w/s--..ws.gif','United States Military Academy','Dogs have been writting letters. ',9);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (32,'Candy','In addition , boxer has been flying away. ','12.09.1985','https:/w|/.ww/w|sssw|/wsw/w|-.//|-|/||w/w..gif','Yale University','Comparatively , old dogs have been running late. ',10);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (55,'Beverages','Therefore , uninterested mates have been driving home. ','06.03.2000','https:|.gif','Wesleyan University','Onversely , cats have woke up early. ',11);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (58,'Body Scrubs','Bus woke up early. ','28.09.1819','https:.png','Stanford University','Then , obedient cars haven''t been writting letters. ',12);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (172,'Alcoholic Beverages','Thereafter , donkeys haven''t been making pancakes. ','08.02.1833','http:ww-//-s/|/w/s/|w/-s|w|/--..jpg','University of Chicago','Hence , proud journalist isn''t writting essays. ',13);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (176,'Air Fresheners','Still , breeze teacher gone home for lunch. ','23.01.2000','http:wss|wswsw-w|//.gif','Harvard University','Nevertheless , John has been making cake. ',14);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (71,'Baby Care','Otherwise , round horse is writting letters. ','09.02.1844','http:-s/s/s|ssss//s-//|s-//sw/|s/-|./|.|s/w//sssss|.sswsww|w|wws//||w|s/sw/sss/s-/||.gif','University of Pennsylvania','Bugs are waiting for the bus. ',15);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (36,'Butters','Comparatively , yummy seal wasn''t escaping. ','30.04.1830','http:s/w|/w|/|sw.s/ss|/-/w.w/s||sw.|-w/w///s||sw//sww-w|sw/-|.gif','Williams College','However , curved car is making cake. ',16);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (176,'Body Lotions','Fighters weren''t flying away. ','12.10.1754','https:ss|||s-s||.|sw-|ss/s||/ww|.sw/w/.jpg','Columbia University','Hence , baker has gone home for lunch. ',17);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (59,'Bread','Now , cuddly John wasn''t flying away. ','22.08.1767','http:/|sss--..|.jpg','Dartmouth College','Similarly , powerful dogs have made cake. ',18);
INSERT INTO SITIOWEBENTITY(AUDIENCIAESPERADA,CATEGORIASITIO,DESCRIPCION,FECHALANZAMIENTO,IMAGEN,NOMBRE,PROPOSITO,PLATAFORMADEDESPLIEGUE_ID) VALUES (43,'Bathroom Cleaners','Namely , rapid soldiers aren''t playing outside. ','17.11.1960','http:|//w/.wwssw|.w.png','Brown University','Drivers waited for the bus. ',19);



INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('udyudi.byyue@hddun.co',5,'Charlotte Robinson','Auditor','ry0pg2csz','+503 8 514 3881',1,1);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('tiior.ktsgkk@prt.org',4,'Sadie Ward','Appraiser','fnd6bho73la','+748 4 958 0723',2,2);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('oljdk.rgkoc@ltj.co',5,'Savannah Perez','Budget Analyst','ymf3eqg1225rc','+811 4 556 3628',3,3);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('rtvhv.foicw@kftj.co',1,'Victoria Gray','Banking Manager','zjo8av8mwm','+824 4 175 2872',4,4);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('umwhcm.tjxma@hch.org',1,'Madison Phillips','Banking Analyst','ju6rhv1hu','+289 6 713 2279',5,5);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('dchvhj.tngubi@wvp.com',2,'Riley Hall','Accountant','rd62tor5teu','+993 1 812 0213',6,6);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('ccevj.xfiri@wsw.com',4,'Anna Lee','Accounting Manager','rea05tt214xs','+173 9 383 5612',7,7);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('hcncgba.sgwuc@wmvo.com',5,'Alyssa Lewis','Banker','fde3478vih7lrk','+585 1 614 6055',8,8);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('medbo.luqijd@nus.org',1,'Emma Hernandez','Assessor','loc7xim34fp','+176 7 647 7164',9,9);
INSERT INTO ADMINISTRADORENTITY(EMAIL,NIVEL,NOMBRE,NOMBRECARGO,PASSWORD,TELEFONO,SITIOWEB_ID,DEPENDENCIA_ID) VALUES ('duezprj.umqin@bfvzwbt.com',1,'Samantha Sanchez','Bookkeeper','pb364wb2gx','+776 3 178 8242',10,10);







